set -e
FullExecPath=$PWD
pushd `dirname $0` > /dev/null
FullScriptPath=`pwd`
popd > /dev/null

#cd $FullScriptPath/../nv-codec-headers
#make PREFIX="$FullScriptPath/../local" install
cd $FullScriptPath/../ffmpeg

export PKG_CONFIG_PATH="$FullExecPath/../local/lib/pkgconfig:$PKG_CONFIG_PATH"
export PATH="$FullExecPath/../gas-preprocessor:$PATH"
echo \#\!/bin/sh > $FullExecPath/../gas-preprocessor/cpp
echo cl \${@:1} >> $FullExecPath/../gas-preprocessor/cpp
chmod a+x $FullExecPath/../gas-preprocessor/cpp

./configure --prefix=$FullScriptPath/../local $ARCH_PARAM \
--toolchain=msvc \
--extra-cflags="-DCONFIG_SAFE_BITSTREAM_READER=1" \
--extra-cxxflags="-DCONFIG_SAFE_BITSTREAM_READER=1" \
--disable-doc \
--disable-everything \
--disable-network \
--disable-programs \
--disable-ffnvcodec \
--disable-cuda-llvm \
--disable-debug \
--enable-stripping \
--enable-small \
--enable-protocol=file \
--enable-libdav1d \
--enable-libopenh264 \
--enable-libopus \
--enable-libvpx \
--enable-dxva2 \
--enable-d3d11va \
--enable-d3d12va \
--enable-filter=atempo \
--enable-filter=scale \
--enable-hwaccels \
--enable-decoder=aac \
--enable-decoder=aac_fixed \
--enable-decoder=aac_latm \
--enable-decoder=ac3 \
--enable-decoder=adpcm_ima_qt \
--enable-decoder=adpcm_ima_wav \
--enable-decoder=adpcm_ms \
--enable-decoder=alac \
--enable-decoder=ape \
--enable-decoder=av1 \
--enable-decoder=cook \
--enable-decoder=dca \
--enable-decoder=dsd_lsbf \
--enable-decoder=dsd_lsbf_planar \
--enable-decoder=dsd_msbf \
--enable-decoder=dsd_msbf_planar \
--enable-decoder=dst \
--enable-decoder=eac3 \
--enable-decoder=flac \
--enable-decoder=flv \
--enable-decoder=gif \
--enable-decoder=h264 \
--enable-decoder=hevc \
--enable-decoder=libdav1d \
--enable-decoder=libvpx_vp8 \
--enable-decoder=libvpx_vp9 \
--enable-decoder=mjpeg \
--enable-decoder=mp1 \
--enable-decoder=mp1float \
--enable-decoder=mp2 \
--enable-decoder=mp2float \
--enable-decoder=mp3 \
--enable-decoder=mp3adu \
--enable-decoder=mp3adufloat \
--enable-decoder=mp3float \
--enable-decoder=mp3on4 \
--enable-decoder=mp3on4float \
--enable-decoder=mpc7 \
--enable-decoder=mpc8 \
--enable-decoder=mpeg2video \
--enable-decoder=mpeg4 \
--enable-decoder=msmpeg4v2 \
--enable-decoder=msmpeg4v3 \
--enable-decoder=opus \
--enable-decoder=pcm_alaw \
--enable-decoder=pcm_f32be \
--enable-decoder=pcm_f32le \
--enable-decoder=pcm_f64be \
--enable-decoder=pcm_f64le \
--enable-decoder=pcm_lxf \
--enable-decoder=pcm_mulaw \
--enable-decoder=pcm_s16be \
--enable-decoder=pcm_s16be_planar \
--enable-decoder=pcm_s16le \
--enable-decoder=pcm_s16le_planar \
--enable-decoder=pcm_s24be \
--enable-decoder=pcm_s24daud \
--enable-decoder=pcm_s24le \
--enable-decoder=pcm_s24le_planar \
--enable-decoder=pcm_s32be \
--enable-decoder=pcm_s32le \
--enable-decoder=pcm_s32le_planar \
--enable-decoder=pcm_s64be \
--enable-decoder=pcm_s64le \
--enable-decoder=pcm_s8 \
--enable-decoder=pcm_s8_planar \
--enable-decoder=pcm_u16be \
--enable-decoder=pcm_u16le \
--enable-decoder=pcm_u24be \
--enable-decoder=pcm_u24le \
--enable-decoder=pcm_u32be \
--enable-decoder=pcm_u32le \
--enable-decoder=pcm_u8 \
--enable-decoder=ra_144 \
--enable-decoder=ra_288 \
--enable-decoder=rv10 \
--enable-decoder=rv20 \
--enable-decoder=rv30 \
--enable-decoder=rv40 \
--enable-decoder=rv60 \
--enable-decoder=sipr \
--enable-decoder=svq1 \
--enable-decoder=svq3 \
--enable-decoder=theora \
--enable-decoder=truehd \
--enable-decoder=vc1 \
--enable-decoder=vc1image \
--enable-decoder=vorbis \
--enable-decoder=vp6 \
--enable-decoder=vp6a \
--enable-decoder=vp6f \
--enable-decoder=vp8 \
--enable-decoder=vp9 \
--enable-decoder=wavpack \
--enable-decoder=wmalossless \
--enable-decoder=wmapro \
--enable-decoder=wmav1 \
--enable-decoder=wmav2 \
--enable-decoder=wmavoice \
--enable-decoder=wmv1 \
--enable-decoder=wmv2 \
--enable-decoder=wmv3 \
--enable-decoder=wmv3image \
--enable-demuxer=aac \
--enable-demuxer=ac3 \
--enable-demuxer=ac4 \
--enable-demuxer=aiff \
--enable-demuxer=ape \
--enable-demuxer=asf \
--enable-demuxer=avi \
--enable-demuxer=caf \
--enable-demuxer=dsf \
--enable-demuxer=dts \
--enable-demuxer=dtshd \
--enable-demuxer=eac3 \
--enable-demuxer=flac \
--enable-demuxer=flv \
--enable-demuxer=gif \
--enable-demuxer=h264 \
--enable-demuxer=hevc \
--enable-demuxer=iff \
--enable-demuxer=m4v \
--enable-demuxer=matroska,webm \
--enable-demuxer=mov,mp4,m4a,3gp,3g2,mj2 \
--enable-demuxer=mp3 \
--enable-demuxer=mpc \
--enable-demuxer=mpc8 \
--enable-demuxer=mpegps \
--enable-demuxer=mpegts \
--enable-demuxer=mpegvideo \
--enable-demuxer=ogg \
--enable-demuxer=rm \
--enable-demuxer=truehd \
--enable-demuxer=wav \
--enable-demuxer=wv \
--enable-demuxer=wtv \
--enable-encoder=aac \
--enable-encoder=libopus \
--enable-encoder=libopenh264 \
--enable-encoder=libvpx_vp9 \
--enable-encoder=pcm_s16le \
--enable-hwaccel=av1_d3d11va \
--enable-hwaccel=av1_d3d11va2 \
--enable-hwaccel=av1_d3d12va \
--enable-hwaccel=av1_dxva2 \
--enable-hwaccel=h264_d3d11va \
--enable-hwaccel=h264_d3d11va2 \
--enable-hwaccel=h264_d3d12va \
--enable-hwaccel=h264_dxva2 \
--enable-hwaccel=hevc_d3d11va \
--enable-hwaccel=hevc_d3d11va2 \
--enable-hwaccel=hevc_d3d12va \
--enable-hwaccel=hevc_dxva2 \
--enable-hwaccel=mpeg2_d3d11va \
--enable-hwaccel=mpeg2_d3d11va2 \
--enable-hwaccel=mpeg2_d3d12va \
--enable-hwaccel=mpeg2_dxva2 \
--enable-hwaccel=vc1_d3d11va \
--enable-hwaccel=vc1_d3d11va2 \
--enable-hwaccel=vc1_d3d12va \
--enable-hwaccel=vc1_dxva2 \
--enable-hwaccel=vp9_d3d11va \
--enable-hwaccel=vp9_d3d11va2 \
--enable-hwaccel=vp9_d3d12va \
--enable-hwaccel=vp9_dxva2 \
--enable-hwaccel=wmv3_d3d11va \
--enable-hwaccel=wmv3_d3d11va2 \
--enable-hwaccel=wmv3_dxva2 \
--enable-muxer=mp4 \
--enable-muxer=ogg \
--enable-muxer=opus \
--enable-muxer=wav \
--enable-muxer=webm \
--enable-parser=aac \
--enable-parser=aac_latm \
--enable-parser=ac3 \
--enable-parser=dca \
--enable-parser=flac \
--enable-parser=gif \
--enable-parser=h264 \
--enable-parser=hevc \
--enable-parser=mpeg4video \
--enable-parser=mpegaudio \
--enable-parser=mpegvideo \
--enable-parser=opus \
--enable-parser=vc1 \
--enable-parser=vorbis \
--enable-parser=vp8 \
--enable-parser=vp9 

cp "$FullScriptPath/iff.c" "$FullScriptPath/../ffmpeg/libavformat/iff.c"
make -j$NUMBER_OF_PROCESSORS
rm -f libavcodec/aarch64/*.d
rm -f libswresample/aarch64/*.d
rm -f libswscale/aarch64/*.d
rm -f libavutil/aarch64/*.d
make -j$NUMBER_OF_PROCESSORS install